### ISSUE TITLE
Issue with running Vanilla install procedure.

### ISSUE THREAD

**Issue by GioValentin** [lucidworks/fusion-cloud-native#43]
ERROR: Unrecognized or misplaced argument: --provider!

Use this script to install Fusion 5 on GKE; optionally create a GKE cluster in the process

Usage: -bash [OPTIONS] ... where OPTIONS include:

  -c            Name of the GKE cluster (required)

  -p            GCP Project ID (required)

  -r            Helm release name for installing Fusion 5, defaults to 'f5'

  -n            Kubernetes namespace to install Fusion 5 into, defaults to 'default'

  -z            GCP Zone to launch the cluster in, defaults to 'us-west1'

  -i            Instance type, defaults to 'e2-standard-8'

  -t            Enable TLS for the ingress, requires a hostname to be specified with -h

  -h            Hostname for the ingress to route requests to this Fusion cluster. If used with the -t parameter,
                then the hostname must be a public DNS record that can be updated to point to the IP of the LoadBalancer

  --prometheus  Enable Prometheus and Grafana for monitoring Fusion services, pass one of: install, provided, none;
                defaults to 'install' which installs Prometheus and Grafana from the stable Helm repo,
                'provided' enables pod annotations on Fusion services to work with Prometheus but does not install anything

  --gke         GKE Master version; defaults to '-' which uses the default version for the selected region / zone (differs between zones)

  --version     Fusion Helm Chart version; defaults to the latest release from Lucidworks, such as 5.0.3-2

  --values      Custom values file containing config overrides; defaults to gke_<cluster>_<namespace>_fusion_values.yaml
                (can be specified multiple times to add additional yaml files, see example-values/*.yaml)

  --num-solr    Number of Solr pods to deploy, defaults to 1

  --node-pool   Node pool label to assign pods to specific nodes, this option is only useful for existing clusters where you defined a custom node pool;
                defaults to 'cloud.google.com/gke-nodepool: default-pool', wrap the arg in double-quotes

  --create      Create a cluster in GKE; provide the mode of the cluster to create, one of: demo, multi_az

  --upgrade     Perform a Helm upgrade on an existing Fusion installation

  --dry-run     Perform a dry-run of the upgrade to see what would change

  --purge       Uninstall and purge all Fusion objects from the specified namespace and cluster.
                Be careful! This operation cannot be undone.

  --force       Force upgrade or purge a deployment if your account is not the value 'owner' label on the namespace

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by ian-thebridge-lucidworks** [comment]
Hi @GioValentin, Which script have you run here? would you be able to provide the arguments that you provided on the command line?

**Comment by GioValentin** [comment]
This is the script that I am running

`bash ./gc_script.sh -c fusion-f5 -p odn-fusion-search -r f5 -z us-east1 -n default --create demo -i e2-standard-8`

**Comment by thelabdude** [comment]
We don't provide a script named `gc_script.sh` so not sure where that is coming from?
