### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

### ISSUE THREAD

**Issue by svanschalkwyk** [lucidworks/fusion-cloud-native#70]
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

kubectl version 1.16
minikube version 1.17.3
helm 3.0.1
Ubuntu 18.04

**Comment by ian-thebridge-lucidworks** [comment]
Which version of the fusion helm chart are you installing? This should be fixed in `5.0.3-4`.

**Comment by svanschalkwyk** [comment]
Thank you. I was trying 5.0.2 as per the docs. 
Seems to install with 5.0.3-4.
