### ISSUE TITLE
typo confirmation for solr auto-scaling policy

### ISSUE THREAD

**Issue by leandro-ciandt** [lucidworks/fusion-cloud-native#89]
hi,

while reading the documentation of this repository, i want to validate the property to set the solr auto-scaling policy, on fusion-admin's definitions.

Q: is it with a typo?
> documentation [link](https://github.com/lucidworks/fusion-cloud-native/blob/master/survival_guide/2_planning.adoc#6-solr-auto-scaling-policy)

--

could you please confirm if should i use `solrAutocalingPolicyJson` or `solrAutoscalingPolicyJson` (or any other property)?

thank you in advance.

**Comment by ian-thebridge-lucidworks** [comment]
The value that is used by the helm chart is `solrAutocalingPolicyJson`, so the documentation is right even though the variable itself looks to be wrong.

**Comment by leandro-ciandt** [comment]
ok, thanks.
